### DISCUSSION TITLE
Recompiling on ANY file change

### DISCUSSION THREAD

**Discussion by JoshReedSchramm** [shakacode/shakapacker#239] [Q&A]
Hi all

Trying to update a rails 6 app to Shakapacker and running into an annoying issue. If I have webpack-dev-server running it will trigger a recompile of assets on a change to any file in the project - including ruby code. 

So if i just update a rails controller it recompiles and reloads in the browser. 

I want this behavior for changes to JS code but not ruby. 

I have these settings in webpacker.yml
```
source_path: app/javascript
source_entry_path: packs
webpack_compile_output: true
webpacker_precompile: true
development:
  <<: *default
  compile: true
  compiler_strategy: mtime
dev_server:
    https: false
    host: localhost
    port: 3035
    hmr: false
    inline_css: true
    client:
      overlay: true
    compress: true
    allowed_hosts: "all"
    pretty: true
    headers:
      'Access-Control-Allow-Origin': '*'
    static:
      watch:
        ignored: '**/node_modules/**'
```

I think that's the relevant bits. Any thoughts? Thanks
