### DISCUSSION TITLE
empty manifest file

### DISCUSSION THREAD

**Discussion by ThePeach** [shakacode/shakapacker#513] [Q&A] [answered]
Hello all, I am currently with Shakapacker v6.5.2, as I'm going through the update from Webpacker v4. 
I just stumbled in a problem that I cannot solve and I was wondering if I am doing anything wrong.
My config file `webpacker.yml`  contains the following:
```yml
default: &default
  source_path: app/assets
  source_entry_path: /javascript
  nested_entries: false
  public_root_path: public
  public_output_path: packs
...
```

But if I try to output the config from my `webpack.config.js` I get:
```js
{
  mode: 'development',
  output: {
    filename: 'js/[name].js',
    chunkFilename: 'js/[name].chunk.js',
    hotUpdateChunkFilename: 'js/[id].[fullhash].hot-update.js',
    path: '/Users/peach/repos/myapp/public/packs',
    publicPath: '/packs/'
  },
  entry: {},
  resolve: {
    extensions: [
      '.js',         '.jsx',
      '.mjs',        '.ts',
      '.tsx',        '.coffee',
      '.mjs',        '.js',
      '.jsx',        '.scss',
      '.css',        '.module.scss',
      '.module.css', '.png',
      '.svg',        '.gif',
      '.jpeg',       '.jpg',
      '.yml'
    ],
    modules: [ '/Users/peach/repos/myapp/app/assets', 'node_modules' ]
  },
....
```

and clearly the `public/packs/manifest.json` is an empty object :(
