### ISSUE TITLE
Allow setting webpack mode to "development" in tests

### ISSUE THREAD

**Issue by AlecRust** [shakacode/shakapacker#126]
Ruby version: 3.1.2
Rails version: 7.0.3
Shakapacker version: 6.2.1

JS `debugger` statements are useful, including when debugging system tests. But in test environment Shakapacker sets webpack to `mode: 'production'` which strips `debugger` statements.

Have you considered providing an option in `webpacker.yml` to set mode to development in `test` environment, to avoid a custom webpack config override?

Or perhaps tests should run with webpack `mode: 'development'` by default? As the builds are faster, with sourcemaps etc.?

**Comment by tomdracz** [comment]
Thanks for raising @AlecRust My take on this is trying to get test environment in the closest state to the production one, hence applying same optimisations. I do see your point around debugging though.

Adding webpack override should be fairly simple although it could use a recipe in the readme maybe to show people how to do it.

I think in general our aim for v7 will be streamlining the config to get this leaner and more customisable and through that we might make things like selecting mode bit easier. With that, I would prefer not adding anything new into `webpacker.yml`.

What's your take @justin808 ?

**Comment by artemave** [comment]
Somewhat relevant: if dev server is running, then webpacker skips compilation and so you get both `mode: development` and source maps in tests. As well as faster test startup.

This wasn't obvious to me until I started reading source code. Perhaps it would be worth mentioning this in the docs.

**Comment by justin808** [comment]
Whether or not this should be in the webpacker.yml would depend on whether or not we can say that the webpack mode should correspond to the RAILS_ENV.

Historically, the NODE_ENV was used to set a particular webpacker configuration file. We removed that in v6.

@artemave if you can submit a doc PR, we'll review it very quickly.

**Comment by Judahmeek** [comment]
Closing as stale

**Comment by justin808** [comment]
We've been doing some experiments using the webpack-dev-server for `RAILS_ENV='test'` and it seems to work well.

It looks something like this.

```yml
# Note: You must restart bin/webpacker-dev-server for changes to take effect
default: &default
  # other settings
   compile: false
development:
  <<: *default

   # Reference: https://webpack.js.org/configuration/dev-server/
   dev_server: &dev_server
     https: false
     host: 0.0.0.0
     port: 3035
    # Hot Module Replacement updates modules while the application is running without a full reload
    hmr: true
    inline: true
    client:
      # Should we show a full-screen overlay in the browser when there are compiler errors or warnings?
      overlay: true

    compress: true
    # Note that apps that do not check the host are vulnerable to DNS rebinding attacks
    allowed_hosts: [ 'localhost' ]
    pretty: true
    headers:
      'Access-Control-Allow-Origin': '*'
    static:
      watch:
        ignored: '**/node_modules/**'

 test: &test
   <<: *default

   dev_server:
     <<: *dev_server

 production:
   <<: *default
   cache_manifest: true
```

First start the weback-dev-server with:  
`RAILS_ENV=development NODE_ENV=development bin/webpacker-dev-server`

Then start your server for development like `NODE_ENV=development RAILS_ENV=development rails s`.

Then you can run a test in development mode by:
`RAILS_ENV=test NODE_ENV=development rspec`

For CI, you can precompile assets with:

`NODE_ENV=production RAILS_ENV=test bin/webpacker`
