### ISSUE TITLE
live reload looping in Safari

### ISSUE THREAD

**Issue by Cervenka** [shakacode/shakapacker#304]
_Notice: A bug is a crash or incorrect behavior. If you have a debugging or troubleshooting question, please open a discussion on the [Discussions Tab](https://github.com/shakacode/shakapacker/discussions). Otherwise, remove this line and fill out the following sections._

## Expected behavior:
When a file gets changed the page should reload once.

## Actual behavior:
When a file gets changed the page continues to reload in a loop in Safari. The state.currentHash never seems to get updated.

## Small, reproducible repo:
https://github.com/Cervenka/webpack-dev-server-reload-issue/

When a pack is included with the option `defer: false` the issue is present, otherwise not. 

## Setup environment:
- Ruby version: 3.0.2
- Rails version: 7.0.4.3
- Shakapacker version: 6.6.0

@alexander-akait, thank you for looking into this as well. 

Thank you!

**Comment by justin808** [comment]
@Cervenka is this more of a documentation issue? What's the proposed fix?

**Comment by alexander-akait** [comment]
@justin808 I jsut think it should not happend at all with and without `defer: false`

**Comment by Cervenka** [comment]
This issue may be related to the default value of `useContentHash`. If I set `useContentHash: true` in shakapacker.yml I don't get a reload loop. Also before enabling that flag Safari cached CSS files even when I disabled caching in the network tab of the dev tools.

This is a part of my current shakapacker.yml config
```
development:
  <<: *default
  compile: false
  compiler_strategy: mtime
  public_output_path: packs-development
  cache_path: tmp/webpacker-development
  useContentHash: true

  dev_server:
    ...
    hmr: true
    inline_css: false
```
