### ISSUE TITLE
Webpack dev server compilation loop

### ISSUE THREAD

**Issue by mariuswestgaard** [shakacode/shakapacker#318]
I have recently installed shakapacker, and whenever I start my devserver (`./bin/webpacker-dev-server`) the devserver starts up, then immediately follows up with an infinite compilation loop.

I'm seeing this in my terminal:
```
npm run dev

> app@0.1.0 dev
> ./bin/webpacker-dev-server

<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:8080/, http://127.0.0.1:8080/
<i> [webpack-dev-server] Content not from webpack is served from '/Website/public' directory
<i> [webpack-dev-server] 404s will fallback to '/index.html'
<i> [webpack-dev-middleware] wait until bundle finished: /packs/js/runtime.js
<i> [webpack-dev-middleware] wait until bundle finished: /packs/js/vendors-node_modules_webpack-dev-server_client_index_js_protocol_ws_3A_hostname_localhost_por-3885b1.js
<i> [webpack-dev-middleware] wait until bundle finished: /packs/js/vendors-node_modules_leaflet-geometryutil_src_leaflet_geometryutil_js-node_modules_leaflet-li-1a372b.js
<i> [webpack-dev-middleware] wait until bundle finished: /packs/js/vendors-node_modules_fit-file-parser_dist_fit-parser_js-node_modules_leaflet_dist_leaflet-src_js.js
<i> [webpack-dev-middleware] wait until bundle finished: /packs/js/vendors-node_modules_react-spinners_BarLoader_js-node_modules_react_ujs_react_ujs_index_js.js
assets by path static/ 189 KiB
  assets by chunk 140 KiB (auxiliary name: application) 25 assets
  assets by chunk 34.6 KiB (auxiliary id hint: vendors) 4 assets
  assets by path static/icons/*.png 14.6 KiB
    asset static/icons/ic-start-6c820c44b10876065bf9.png 7.32 KiB [emitted] [immutable] [from: app/javascript/images/icons/ic-start.png]
    asset static/icons/ic-end-607e3f1758257c53f1f2.png 7.24 KiB [emitted] [immutable] [from: app/javascript/images/icons/ic-end.png]
assets by path js/ 5.16 MiB
  assets by path js/*.js 5.04 MiB 16 assets
  assets by path js/activities/*.js 33.8 KiB 2 assets
  assets by path js/contests/*.js 26.9 KiB 2 assets
  asset js/active_admin/print.js 56.5 KiB [emitted] (name: active_admin/print) 1 related asset
  asset js/segments/show.js 6.23 KiB [emitted] (name: segments/show) 1 related asset
asset manifest.json 13.5 KiB [emitted]
webpack 5.87.0 compiled successfully in 3630 ms
<i> [webpack-dev-middleware] wait until bundle finished: /packs/static/icons/ic-exit-b9500cc4af82c5f129e3.svg
<i> [webpack-dev-middleware] wait until bundle finished: /packs/js/vendors-node_modules_jquery_dist_jquery_js.js
<i> [webpack-dev-middleware] wait until bundle finished: /packs/js/runtime.js
<i> [webpack-dev-middleware] wait until bundle finished: /packs/static/logo-b06371d7660308d51b5e.svg
<i> [webpack-dev-middleware] wait until bundle finished: /packs/js/vendors-node_modules_webpack-dev-server_client_index_js_protocol_ws_3A_hostname_localhost_por-3885b1.js
assets by status 5.34 MiB [cached] 53 assets
asset manifest.json 13.5 KiB [emitted]
webpack 5.87.0 compiled successfully in 36011 ms
<i> [webpack-dev-middleware] wait until bundle finished: /packs/static/logo-b06371d7660308d51b5e.svg
<i> [webpack-dev-middleware] wait until bundle finished: /packs/js/vendors-node_modules_jquery_dist_jquery_js.js
<i> [webpack-dev-middleware] wait until bundle finished: /packs/js/vendors-node_modules_react-spinners_BarLoader_js-node_modules_react_ujs_react_ujs_index_js.js
<i> [webpack-dev-middleware] wait until bundle finished: /packs/static/icons/ic-exit-b9500cc4af82c5f129e3.svg
<i> [webpack-dev-middleware] wait until bundle finished: /packs/js/vendors-node_modules_leaflet-geometryutil_src_leaflet_geometryutil_js-node_modules_leaflet-li-1a372b.js
assets by status 5.34 MiB [cached] 53 assets
asset manifest.json 13.5 KiB [emitted]
webpack 5.87.0 compiled successfully in 436 ms
<i> [webpack-dev-middleware] wait until bundle finished: /packs/js/app_javascript_src_js_mapHandler_js.js
<i> [webpack-dev-middleware] wait until bundle finished: /packs/js/vendors-node_modules_rails_activestorage_app_assets_javascripts_activestorage_js-node_modules-8f6dfe.js
<i> [webpack-dev-middleware] wait until bundle finished: /packs/js/app_javascript_components_sync_recursive_.js
<i> [webpack-dev-middleware] wait until bundle finished: /packs/js/app_javascript_packs_global_js.js
assets by status 5.34 MiB [cached] 53 assets
asset manifest.json 13.5 KiB [emitted]
webpack 5.87.0 compiled successfully in 388 ms
<i> [webpack-dev-middleware] wait until bundle finished: /packs/js/vendors-node_modules_fit-file-parser_dist_fit-parser_js-node_modules_leaflet_dist_leaflet-src_js.js
assets by status 5.34 MiB [cached] 53 assets
asset manifest.json 13.5 KiB [emitted]
webpack 5.87.0 compiled successfully in 370 ms
assets by status 5.34 MiB [cached] 53 assets
asset manifest.json 13.5 KiB [emitted]
webpack 5.87.0 compiled successfully in 361 ms
assets by status 5.34 MiB [cached] 53 assets
asset manifest.json 13.5 KiB [emitted]
webpack 5.87.0 compiled successfully in 355 ms
assets by status 5.34 MiB [cached] 53 assets
asset manifest.json 13.5 KiB [emitted]
webpack 5.87.0 compiled successfully in 366 ms
assets by status 5.34 MiB [cached] 53 assets
asset manifest.json 13.5 KiB [emitted]
webpack 5.87.0 compiled successfully in 354 ms
assets by status 5.34 MiB [cached] 53 assets
asset manifest.json 13.5 KiB [emitted]
webpack 5.87.0 compiled successfully in 366 ms
assets by status 5.34 MiB [cached] 53 assets
asset manifest.json 13.5 KiB [emitted]
webpack 5.87.0 compiled successfully in 395 ms
assets by status 5.34 MiB [cached] 53 assets
asset manifest.json 13.5 KiB [emitted]
webpack 5.87.0 compiled successfully in 352 ms
assets by status 5.34 MiB [cached] 53 assets
asset manifest.json 13.5 KiB [emitted]
webpack 5.87.0 compiled successfully in 369 ms
assets by status 5.34 MiB [cached] 53 assets
asset manifest.json 13.5 KiB [emitted]
webpack 5.87.0 compiled successfully in 353 ms
assets by status 5.34 MiB [cached] 53 assets
asset manifest.json 13.5 KiB [emitted]
webpack 5.87.0 compiled successfully in 350 ms
assets by status 5.34 MiB [cached] 53 assets
asset manifest.json 13.5 KiB [emitted]
webpack 5.87.0 compiled successfully in 353 ms
assets by status 5.34 MiB [cached] 53 assets
asset manifest.json 13.5 KiB [emitted]
webpack 5.87.0 compiled successfully in 357 ms
assets by status 5.34 MiB [cached] 53 assets
asset manifest.json 13.5 KiB [emitted]
webpack 5.87.0 compiled successfully in 346 ms
assets by status 5.34 MiB [cached] 53 assets
asset manifest.json 13.5 KiB [emitted]
webpack 5.87.0 compiled successfully in 361 ms
assets by status 5.34 MiB [cached] 53 assets
asset manifest.json 13.5 KiB [emitted]
webpack 5.87.0 compiled successfully in 349 ms
assets by status 5.34 MiB [cached] 53 assets

(then just continues like this forever)
```

In my webpacker.yml file I'm having these settings:

```
default: &default
  source_path: app/javascript
  source_entry_path: packs

  nested_entries: true

  css_extract_ignore_order_warnings: false

  public_root_path: public
  public_output_path: packs
  cache_path: tmp/webpacker
  webpack_compile_output: false
  webpacker_precompile: true

  additional_paths: []

  cache_manifest: false

  webpack_loader: 'babel'

  ensure_consistent_versioning: true

  compiler_strategy: digest

development:
  <<: *default
  compile: true
  compiler_strategy: mtime

  dev_server:
    https: false
    host: localhost
    port: 8080

    hmr: true

    inline_css: true

    # live_reload: false
    client:
      overlay: true
     
    compress: true

    allowed_hosts: 'all'

    pretty: true
    headers:
      'Access-Control-Allow-Origin': '*'
    static:
      watch:
        ignored: '**/node_modules/**'

test:
  <<: *default
  compile: true

  public_output_path: packs-test

production:
  <<: *default

  compile: false

  cache_manifest: true
```

My CSR setting: 
`policy.connect_src :self, :https, "http://localhost:8080", "ws://localhost:8080" if Rails.env.development?`

I've been playing around with `hmr`, `inline_css` and `live_reload` settings with no success (no difference).

I can't seem to pinpoint where this problem is coming from. Any tips on providing more details is appreciated.

## Expected behavior:
I'd expect the devserver to recompile once, only when a watched file is changed.

## Actual behavior:
Devserver starts up, and follows up with an infinite loop.

## Setup environment:
- Ruby version: 2.7.8
- Rails version: 6.1.7.2
- Shakapacker version: 6.6.0
- Webpack: 5.87.0
- Webpack-dev-server: 4.9.0
