### ISSUE TITLE
Receiving WebSocket connect to 'wss://hostname:3035/ws' failed

### ISSUE THREAD

**Issue by RailsCod3rFuture** [shakacode/shakapacker#50]
During deployments to dev/production servers, everything works perfectly fine with websockets. Now, I am trying to use shakapacker on Docker and I receive "Unable to process ChannelName#action" Is there anything specific that I have to do, in order to communicate with web sockets using this version? I'm running Redis on the same container as the rails app and I am able to connect to it using 127.0.0.1. Every time that I use docker, I see [webpack-dev-server] Trying to reconnect.....? WebSocketClient @ WebSocketClient.js.

**Comment by tomdracz** [comment]
If anything you might be facing Webpack rather than Shakapacker change. Default socket communication has changed from sockjs to native websocket (https://webpack.js.org/configuration/dev-server/#devserverwebsocketserver) - if you weren't using `ws` communication explicitly before, that might be a change for you.

You will need to play around with the dev server config and/or your docker setup. Try modifying it to use `sockjs` again or make necessary changes in your docker setup to accommodate for the ws sockets. Either way, it's not a Webpacker issues.

Might not be matching what you have there but I had to change the following to get everything working smoothly with locals Rails app but connecting through dockerised nginx.

In dev server config in `webpacker.yml`
```
  dev_server:
    https: false
    host: '0.0.0.0'
    port: 3035
    client:
      webSocketURL:
        hostname: 'myhost.test'
        pathname: '/ws'
        port: 443
        protocol: 'wss'
 ...
```

In nginx config, new path added:

```
  location /ws {
    proxy_pass http://${DOCKER_HOST_IP}:${WEBPACKER_PORT};
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header    Upgrade $http_upgrade;
    proxy_set_header    Connection "upgrade";
  }
  ```
