### ISSUE TITLE
Setting different URL for pack tags

### ISSUE THREAD

**Issue by krystof-k** [shakacode/shakapacker#95]
I'm migrating from Webpacker 5 to Shakapacker and option `development.dev_server.public: localhost:3035` in `config/webpacker.yaml` is no longer working.

Since we use separate Docker container to run webpacker-dev-server, I need the pack tags URLs to contain the different port.

I also tried setting `dev_server.devMiddleware.publicPath` but that doesn't have any effect either.

According to the getPublicPath function,
https://github.com/shakacode/shakapacker/blob/b4ecde115a9676ae23b0c70a2118db65bcdec3f2/package/config.js#L22
I tried setting `WEBPACKER_ASSET_HOST` environment variable, which worked, but doesn't feel like a proper solution.

**Comment by tomdracz** [comment]
@krystof-k If you're migrating from `dev_server.public` option you might need to use `dev_server.client` instead as that changed in the webpack setup. It does sound like it's not quite that. I'm thoroughly confused by the publicPath vs client config in webpack.

If you are looking to set the public path, it does seem like `WEBPACKER_ASSET_HOST` is the only way to set it up at the moment. Agree that having this as a webpacker config option might be reasonable.

Don't know that much about setups like that though, any thoughts @justin808 ?

**Comment by krystof-k** [comment]
I'm using the default for `dev_server.client` and seems to be working all right (however I've not yet tried setting up HMR). This issue was meant to be mainly about setting the URL for pack tags.

Just not sure about the piece of code I linked above, maybe it should just respect the Webpack config.

**Comment by jwoodrow** [comment]
Hi @krystof-k, I was curious how you got shakapacker (webpacker-dev-server) to work well with rails using docker ?

Because I'm currently encountering an issue where everything builds fine but once I try accessing any page, the rails service can't seem to connect to the webpacker service and ends up recompiling webpack which kind of defeats the purpose of having webpacker-dev-server to reload code automatically

**Comment by krystof-k** [comment]
Hi @jwoodrow, my Docker Compose, in a nutshell, looks like this:

```yaml
services:
  web:
    environment:
      APP_HOST: localhost
      APP_PORT: 3000
      WEBPACKER_ASSET_HOST: http://localhost:3035
      WEBPACKER_DEV_SERVER_HOST: webpack-dev-server
    ports:
      - 3000:3000
    depends_on:
      webpacker-dev-server:
        condition: service_started
    command: bundle exec rails server -b '0.0.0.0'
  webpacker-dev-server:
    extends:
      service: development
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - 3035:3035
    command: bundle exec bin/webpacker-dev-server
```

Then in webpacker.yml, I have:

```yaml
development:
  compile: false
  dev_server:
    https: false
    host: localhost
    port: 3035
```

Feel free to reach me at krystof@korb.cz in case it didn't work out, I'll try to help :)
