### ISSUE TITLE
Assets not built for tests in CI

### ISSUE THREAD

**Issue by AlecRust** [shakacode/shakapacker#96]
When `compile` in Test environment is set to `true`, Shakapacker automatically builds to `/public/packs-test`.

`webpacker.yml`
```yaml
test:
  <<: *default
  compile: true
```

However in CI e.g. CircleCI this does not happen, tests run without automatically building the assets.

- Is it correct that Shakapacker does not automatically build in this CI environment, where `RAILS_ENV` etc. is set to `test`? This was slightly unexpected when I changed this setting (in place of manually calling `Webpacker.compile` in our test helpers).
- If it is correct, what is the official way of building assets for tests in a CI environment? Heroku runs `bundle exec rake assets:precompile` in Production, is it the same command in CI? Happy to update the docs with the recommended setup here.

**Comment by tomdracz** [comment]
@AlecRust What's the behaviour you are expecting here?

- `compile: true` automatically precompiles ALL of the assets?
- `compile: true` compiles asset on demand when you are trying to reference them?

The behaviour we have is the latter - https://github.com/shakacode/shakapacker/blob/master/lib/webpacker/manifest.rb#L22 essentially if `compile` is set to `true` and dev server is not running, every asset request should be preceded with compilation. If that doesn't work, let us know and we will investigate further as it SHOULD work.

II'm running setup on CircleCI and we're explicitly compiling assets before the test run to avoid that compilation on every lookup step. So the "official" way will be that, you have to run `bundle exec rake assets:precompile` somewhere before the tests for the best performance.

For reference, our setup for this on CircleCI pipeline is something like below (includes caching so we can shave off some time on the builds where we don't touch assets):

```
      compile-assets:
        description: 'Precompiles and caches the webpacker assets'
        steps:
          - run:
              name: Set up assets cache key
              command: find app/frontend -type f -exec md5sum {} \; > dependency_checksum
          - restore_cache:
              name: Restore assets cache
              keys:
                - assets-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "dependency_checksum" }}
                - assets-cache-v1-{{ arch }}-{{ .Branch }}
                - assets-cache-v1-{{ arch }}
                - assets-cache-v1
          - run:
              name: Precompile assets
              command: RAILS_ENV=test bundle exec rails webpacker:compile
          - save_cache:
              name: Save assets cache
              paths:
                - public/packs-test
                - tmp/cache/webpacker
              key: assets-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "dependency_checksum" }}
```

**Comment by AlecRust** [comment]
Thanks for your detailed reply @tomdracz.

I guess I would expect in CI (where `RAILS_ENV=test` is set etc.) either of those two to happen, but neither is happening for us in CI environment in my testing..

The former sounds like it would provide performance most appropriate for CI, though the latter is more consistent with behaviour in Development.

We have up until now been calling `Webpacker.compile` in our test helpers. I'm looking to better match the defaults by setting `compile: true`, but I see assets must be built manually in CI.

To be clear I'm now running `bundle exec rake assets:precompile` before the tests, but I expected that to happen automatically.

Thank you for the CircleCI snippet with caching, very useful.

**Comment by tomdracz** [comment]
> I guess I would expect in CI (where RAILS_ENV=test is set etc.) either of those two to happen, but neither is happening for us in CI environment in my testing..

This is not what I would expect. I'll play around with our CI and see what I'll get and whether I spot any problems.

> To be clear I'm now running bundle exec rake assets:precompile before the tests, but I expected that to happen automatically.

Might be one to clear up in docs to specify that the options is meant to provide on the fly compilation rather than precompilation hooking up to anything else!

**Comment by AlecRust** [comment]
Thanks again @tomdracz. Not sure why the automatic compilation isn't working for us, but sounds like manual compilation is better anyway.

I guess we can close this issue, but a couple more points that may be of interest:

- I note that `NODE_ENV=test` needs to be set in CI when compiling manually, this wasn't necessary when we called `Webpacker.compile` in the test helpers which is slightly odd.
- I tried your example of caching the assets, and although it seems to work (cache is restored to correct location with correct identical content to the output of `webpacker:compile`) Shakapacker seems to always recompile the assets, even though they are already there.

For example:
```yaml
build_assets:
  description: "Precompiles and caches Shakapacker assets"
  steps:
    - run:
        name: Setting up assets cache key
        command: find app/packs -type f -exec md5sum {} \; > assets_checksum.txt
    - restore_cache:
        name: Restoring assets cache
        keys:
          - assets-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "assets_checksum.txt" }}
          - assets-cache-v1-{{ arch }}-{{ .Branch }}
          - assets-cache-v1-{{ arch }}
          - assets-cache-v1
    - run:
        name: Precompiling assets
        command: bundle exec rails webpacker:compile
    - save_cache:
        name: Saving assets cache
        key: assets-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "assets_checksum.txt" }}
        paths:
          - public/packs-test
          - tmp/cache/webpacker
```

hen `bundle exec rails webpacker:compile` is run I expect the output I get locally when testing:

```sh
D, [2022-04-05T18:20:26.788438 #12496] DEBUG -- : Everything's up-to-date. Nothing to do
```

But instead the job takes 30+ seconds and always has the output:

```sh
I, [2022-04-05T17:06:24.438308 #469]  INFO -- : Compiling...
I, [2022-04-05T17:06:50.623964 #469]  INFO -- : Compiled all packs in /home/circleci/project/public/packs-test
```

Would just be nice to confirm that this is indeed working for you, and you get the "Everything's up-to-date" output?
